
// This file was generated by Intellego. Do not modify

class RealSe101Robot
{
	public static void main(String args[])
	{
		Se101Robot a=new Se101Robot();
		a.initController(new real.RealRCX(a));
		a.run();
	}
}