
// This file was generated by Intellego. Do not modify

class RealZincRocker
{
	public static void main(String args[])
	{
		ZincRocker a=new ZincRocker();
		a.initController(new real.RealRCX(a));
		a.run();
	}
}